In [138]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set()
import warnings
warnings.filterwarnings('ignore')

# Reading the data

In [141]:
data1 = pd.read_csv('nyc_subway.csv')
data1.head(2)

,Division,Line,Station Name,Station Latitude,Station Longitude,Route1,Route2,Route3,Route4,Route5,...,Free Crossover,North South Street,East West Street,Corner,Entrance Latitude,Entrance Longitude,Station Location,Entrance Location,entrance_georeference,station_georeference
0,BMT,Brighton,West 8th St,40.576127,-73.975939,F,Q,NaN,NaN,NaN,...,True,NaN,NaN,NaN,40.575752,-73.976740,"(40.576127, -73.975939)","(40.575752, -73.97674)",POINT (-73.97674 40.575752),POINT (-73.975939 40.576127)
1,BMT,Brighton,West 8th St,40.576127,-73.975939,F,Q,NaN,NaN,NaN,...,True,NaN,NaN,NaN,40.576464,-73.974862,"(40.576127, -73.975939)","(40.576464, -73.974862)",POINT (-73.974862 40.576464),POINT (-73.975939 40.576127)

In [145]:
data2 = pd.read_csv('nyc_subway.csv',header = None)
data2.head(2) 
# Whenever there is no header in the csv file

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,Division,Line,Station Name,Station Latitude,Station Longitude,Route1,Route2,Route3,Route4,Route5,...,Free Crossover,North South Street,East West Street,Corner,Entrance Latitude,Entrance Longitude,Station Location,Entrance Location,entrance_georeference,station_georeference
1,BMT,Brighton,West 8th St,40.576127,-73.975939,F,Q,NaN,NaN,NaN,...,TRUE,NaN,NaN,NaN,40.575752,-73.97674,"(40.576127, -73.975939)","(40.575752, -73.97674)",POINT (-73.97674 40.575752),POINT (-73.975939 40.576127)

In [144]:
data3 = pd.read_csv('nyc_subway.csv',header = None, names = ['a','b','c'])
data3.head(2) 
# assigning names to columns

,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,a,b,c
Division,Line,Station Name,Station Latitude,Station Longitude,Route1,Route2,Route3,Route4,Route5,Route6,Route7,Route8,Route9,Route10,Route11,Entrance Type,Entry,Exit Only,Vending,Staffing,Staff Hours,ADA,ADA Notes,Free Crossover,North South Street,East West Street,Corner,Entrance Latitude,Entrance Longitude,Station Location,Entrance Location,entrance_georeference,station_georeference
BMT,Brighton,West 8th St,40.576127,-73.975939,F,Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ramp,YES,NaN,NO,NONE,NaN,FALSE,NaN,TRUE,NaN,NaN,NaN,40.575752,-73.97674,"(40.576127, -73.975939)","(40.575752, -73.97674)",POINT (-73.97674 40.575752),POINT (-73.975939 40.576127)

# describing the dataset

In [148]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [153]:
data.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [150]:
data.describe(include = 'all')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
count,1460.000000,1460.000000,1460,1201.000000,1460.000000,1460,91,1460,1460,1460,...,1460.000000,7,281,54,1460.000000,1460.000000,1460.000000,1460,1460,1460.000000
unique,NaN,NaN,5,NaN,NaN,2,2,4,4,2,...,NaN,3,4,4,NaN,NaN,NaN,9,6,NaN
top,NaN,NaN,RL,NaN,NaN,Pave,Grvl,Reg,Lvl,AllPub,...,NaN,Gd,MnPrv,Shed,NaN,NaN,NaN,WD,Normal,NaN
freq,NaN,NaN,1151,NaN,NaN,1454,50,925,1311,1459,...,NaN,3,157,49,NaN,NaN,NaN,1267,1198,NaN
mean,730.500000,56.897260,NaN,70.049958,10516.828082,NaN,NaN,NaN,NaN,NaN,...,2.758904,NaN,NaN,NaN,43.489041,6.321918,2007.815753,NaN,NaN,180921.195890
std,421.610009,42.300571,NaN,24.284752,9981.264932,NaN,NaN,NaN,NaN,NaN,...,40.177307,NaN,NaN,NaN,496.123024,2.703626,1.328095,NaN,NaN,79442.502883
min,1.000000,20.000000,NaN,21.000000,1300.000000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,1.000000,2006.000000,NaN,NaN,34900.000000
25%,365.750000,20.000000,NaN,59.000000,7553.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,5.000000,2007.000000,NaN,NaN,129975.000000
50%,730.500000,50.000000,NaN,69.000000,9478.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,6.000000,2008.000000,NaN,NaN,163000.000000
75%,1095.250000,70.000000,NaN,80.000000,11601.500000,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.000000,8.000000,2009.000000,NaN,NaN,214000.000000
max,1460.000000,190.000000,NaN,313.000000,215245.000000,NaN,NaN,NaN,NaN,NaN,...,738.000000,NaN,NaN,NaN,15500.000000,12.000000,2010.000000,NaN,NaN,755000.000000

In [151]:
data.describe(include = 'object')

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1460,91,1460,1460,1460,1460,1460,1460,1460,...,1379,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,2,2,4,4,2,5,3,25,9,...,6,3,5,5,3,3,4,4,9,6
top,RL,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,...,Attchd,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,1454,50,925,1311,1459,1052,1382,225,1260,...,870,605,1311,1326,1340,3,157,49,1267,1198

In [152]:
data.describe(include = ['object','float'])

,MSZoning,LotFrontage,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,...,GarageYrBlt,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
count,1460,1201.000000,1460,91,1460,1460,1460,1460,1460,1460,...,1379.000000,1379,1379,1379,1460,7,281,54,1460,1460
unique,5,NaN,2,2,4,4,2,5,3,25,...,NaN,3,5,5,3,3,4,4,9,6
top,RL,NaN,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,NAmes,...,NaN,Unf,TA,TA,Y,Gd,MnPrv,Shed,WD,Normal
freq,1151,NaN,1454,50,925,1311,1459,1052,1382,225,...,NaN,605,1311,1326,1340,3,157,49,1267,1198
mean,NaN,70.049958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1978.506164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,24.284752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.689725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,21.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1900.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,59.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1961.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,69.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1980.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,80.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2002.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,313.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2010.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# also describe function can be applicable to filtered datas also

# Applying Filters

In [154]:
data.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [156]:
data[data.MSSubClass == 60].head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500

In [157]:
data[(data.MSSubClass == 60)&(data.LotArea >= 10000)].head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [ ]:
# similar way we can use any logical operators

In [161]:
data[data.Street == 'Pave'].head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [165]:
data[data.Street.isin(['Grvl'])].head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
52,53,90,RM,110.0,8472,Grvl,NaN,IR2,Bnk,AllPub,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,110000
335,336,190,RL,NaN,164660,Grvl,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,Shed,700,8,2008,WD,Normal,228950

In [164]:
data.Street.unique()

array(['Pave', 'Grvl'], dtype=object)

# dataset subset

In [166]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [168]:
data4 = pd.DataFrame(data,columns = ['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood'])
data4.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker

# sort values

In [170]:
data.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [174]:
data.MSSubClass.sort_values()

1459     20
888      20
889      20
892      20
893      20
       ...
520     190
1266    190
48      190
1062    190
861     190
Name: MSSubClass, Length: 1460, dtype: int64

In [173]:
data.MSSubClass.sort_values(ascending = False).head()

246     190
1062    190
1190    190
635     190
637     190
Name: MSSubClass, dtype: int64

In [175]:
data.sort_values('MSSubClass').head() # sorting the entire dataset based on the feature

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500
888,889,20,RL,95.0,15865,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2007,WD,Normal,268000
889,890,20,RL,128.0,12160,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2009,WD,Normal,149500
892,893,20,RL,70.0,8414,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2006,WD,Normal,154500
893,894,20,RL,NaN,13284,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,6,2008,WD,Normal,165000

In [177]:
data.sort_values(['MSSubClass','LotFrontage'],ascending = False).head() # sorting the entire dataset based on two  feature

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1186,1187,190,RL,107.0,10615,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,8,2009,WD,Abnorml,95000
411,412,190,RL,100.0,34650,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,1,2006,WD,Normal,145000
300,301,190,RL,90.0,15750,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,157000
1062,1063,190,RM,85.0,13600,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2007,WD,Normal,90000
703,704,190,RM,76.0,7630,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2010,WD,Normal,140000

In [ ]:
# change or adjust the display of num of rows and columns

In [178]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller then the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.column_space No description available.
    [default: 12] [currently: 12]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table (the default from 0.13), or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.latex.escape : bool
    This specifies if the to_latex method of a Dataframe uses escapes special
    characters.
    Valid values: False,True
    [default: True] [currently: True]
display.latex.longtable :bool
    This specifies if the to_latex method of a Dataframe uses the longtable
    format.
    Valid values: False,True
    [default: False] [currently: False]
display.latex.multicolumn : bool
    This specifies if the to_latex method of a Dataframe uses multicolumns
    to pretty-print MultiIndex columns.
    Valid values: False,True
    [default: True] [currently: True]
display.latex.multicolumn_format : bool
    This specifies if the to_latex method of a Dataframe uses multicolumns
    to pretty-print MultiIndex columns.
    Valid values: False,True
    [default: l] [currently: l]
display.latex.multirow : bool
    This specifies if the to_latex method of a Dataframe uses multirows
    to pretty-print MultiIndex rows.
    Valid values: False,True
    [default: False] [currently: False]
display.latex.repr : boolean
    Whether to produce a latex DataFrame representation for jupyter
    environments that support it.
    (default: False)
    [default: False] [currently: False]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 20] [currently: 20]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int or None
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd.
    [default: auto] [currently: auto]
io.excel.xls.writer : string
    The default Excel writer engine for 'xls' files. Available options:
    auto, xlwt.
    [default: auto] [currently: auto]
    (Deprecated, use `` instead.)
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.data_manager : string
    Internal data manager type; can be "block" or "array". Defaults to "block",
    unless overridden by the 'PANDAS_DATA_MANAGER' environment variable (needs
    to be set before pandas is imported).
    [default: block] [currently: block]
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.string_storage : string
    The default storage for StringDtype.
    [default: python] [currently: python]
mode.use_inf_as_na : boolean
    True means treat None, NaN, INF, -INF as NA (old way),
    False means None and NaN are null, but INF, -INF are not NA
    (new way).
    [default: False] [currently: False]
mode.use_inf_as_null : boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.
    [default: False] [currently: False]
    (Deprecated, use `mode.use_inf_as_na` instead.)
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satsify ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satsify ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

In [182]:
pd.set_option('display.max_columns',1000)

# Ranking

In [183]:
data.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500

In [184]:
data.rank()  # shows rank of the feature variable

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1.0,915.0,667.0,522.5,510.5,733.5,NaN,998.0,805.0,730.0,934.5,691.5,196.5,759.5,731.0,610.5,1136.0,1072.0,499.0,1162.0,1058.0,584.0,718.5,971.0,973.5,238.0,1146.5,310.5,819.5,1104.0,465.5,768.0,946.0,577.5,1091.5,794.5,647.0,259.0,474.0,715.5,371.0,778.0,792.5,307.0,1222.0,717.5,1025.0,1150.5,689.5,1043.5,1181.0,816.5,697.5,432.5,1215.0,780.5,345.5,NaN,441.5,1075.5,563.5,862.5,997.5,724.0,716.5,790.5,381.0,1049.0,626.5,718.5,672.5,727.0,NaN,NaN,NaN,704.5,84.5,795.5,827.0,736.5,1072.0
1,2.0,268.5,667.0,883.0,767.5,733.5,NaN,998.0,805.0,730.0,381.0,691.5,1455.0,89.0,731.0,610.5,531.5,725.5,1402.5,775.0,514.5,584.0,718.5,468.5,440.5,892.5,431.0,1007.5,819.5,463.5,465.5,768.0,288.5,110.5,1265.0,794.5,647.0,447.5,1068.5,715.5,371.0,778.0,792.5,968.5,415.0,717.5,511.5,428.5,1418.5,1043.5,457.0,816.5,697.5,1093.0,591.5,780.5,1015.5,614.0,441.5,603.0,563.5,862.5,667.0,724.0,716.5,790.5,1355.0,328.5,626.5,718.5,672.5,727.0,NaN,NaN,NaN,704.5,459.5,479.0,827.0,736.5,909.0
2,3.0,915.0,667.0,581.0,1051.5,733.5,NaN,242.5,805.0,730.0,934.5,691.5,196.5,759.5,731.0,610.5,1136.0,1072.0,499.0,1106.5,1008.5,584.0,718.5,971.0,973.5,238.0,1083.5,310.5,819.5,1104.0,465.5,768.0,412.5,577.5,829.5,794.5,647.0,681.0,612.5,715.5,371.0,778.0,792.5,445.5,1238.0,717.5,1100.0,1150.5,689.5,1043.5,1181.0,816.5,697.5,432.5,591.5,780.5,1015.5,614.0,441.5,1014.5,563.5,862.5,1150.5,724.0,716.5,790.5,381.0,894.5,626.5,718.5,672.5,727.0,NaN,NaN,NaN,704.5,1202.0,795.5,827.0,736.5,1135.5
3,4.0,1094.5,667.0,376.0,745.0,733.5,NaN,242.5,805.0,730.0,132.0,691.5,297.0,759.5,731.0,610.5,1136.0,1072.0,499.0,64.5,420.5,584.0,718.5,1331.5,1441.5,892.5,431.0,1007.5,819.5,73.5,1099.0,78.0,946.0,110.5,582.5,794.5,647.0,797.0,297.0,715.5,911.0,778.0,792.5,519.5,1130.0,717.5,1036.0,1150.5,689.5,334.5,457.0,816.5,697.5,432.5,957.0,780.5,1015.5,247.5,1186.0,932.0,1077.0,1365.0,1198.0,724.0,716.5,790.5,381.0,812.0,1449.0,718.5,672.5,727.0,NaN,NaN,NaN,704.5,84.5,157.5,827.0,51.0,499.5
4,5.0,915.0,667.0,945.0,1310.0,733.5,NaN,242.5,805.0,730.0,381.0,691.5,932.0,759.5,731.0,610.5,1136.0,1315.5,499.0,1084.5,936.0,584.0,718.5,971.0,973.5,238.0,1326.0,310.5,819.5,1104.0,465.5,768.0,111.0,577.5,1022.5,794.5,647.0,747.0,953.0,715.5,371.0,778.0,792.5,828.5,1353.0,717.5,1323.0,1150.5,689.5,1043.5,1181.0,1325.0,697.5,432.5,1346.0,780.5,1015.5,614.0,441.5,991.0,563.5,1365.0,1372.0,724.0,716.5,790.5,1167.5,1172.5,626.5,718.5,672.5,727.0,NaN,NaN,NaN,704.5,1431.0,795.5,827.0,736.5,1239.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456.0,915.0,667.0,460.0,417.5,733.5,NaN,998.0,805.0,730.0,934.5,691.5,462.0,759.5,731.0,610.5,1136.0,725.5,499.0,1060.0,936.0,584.0,718.5,971.0,973.5,892.5,431.0,1007.5,819.5,1104.0,465.5,768.0,946.0,1208.5,234.0,794.5,647.0,1207.5,673.5,715.5,371.0,778.0,792.5,496.5,1053.0,717.5,947.0,428.5,689.5,1043.5,1181.0,816.5,697.5,1093.0,957.0,780.5,1015.5,614.0,441.5,962.5,563.5,862.5,667.0,724.0,716.5,790.5,381.0,878.0,626.5,718.5,672.5,727.0,NaN,NaN,NaN,704.5,1109.5,479.0,827.0,736.5,832.0
1456,1457.0,268.5,667.0,969.5,1243.0,733.5,NaN,998.0,805.0,730.0,934.5,691.5,875.0,759.5,731.0,610.5,531.5,725.5,1035.5,831.5,648.0,584.0,718.5,632.5,619.5,1388.5,1018.0,1007.5,819.5,463.5,465.5,768.0,946.0,110.5,1163.5,139.5,1328.0,851.0,1278.0,715.5,1246.5,778.0,792.5,1431.0,415.0,717.5,1275.0,1150.5,689.5,1043.5,457.0,816.5,697.5,1093.0,957.0,35.0,1398.0,614.0,441.5,662.0,1077.0,862.5,828.5,724.0,716.5,790.5,1394.5,328.5,626.5,718.5,672.5,727.0,NaN,192.0,NaN,704.5,84.5,1373.0,827.0,736.5,1078.0
1457,1458.0,1094.5,667.0,552.0,645.5,733.5,NaN,998.0,805.0,730.0,934.5,691.5,297.0,759.5,731.0,610.5,1136.0,1072.0,1449.5,265.0,1267.0,584.0,718.5,105.0,86.5,892.5,431.0,26.5,104.5,1454.5,1099.0,78.0,946.0,577.5,622.5,794.5,647.0,1150.0,960.0,715.5,371.0,778.0,792.5,882.5,1391.0,717.5,1361.0,428.5,689.5,1043.5,457.0,1325.0,697.5,432.5,1346.0,780.5,1398.0,247.5,441.5,128.5,563.5,266.0,178.0,724.0,716.5,790.5,381.0,1040.0,626.5,718.5,672.5,727.0,NaN,30.0,29.0,1457.0,459.5,1373.0,827.0,736.5,1285.0
1458,1459.0,268.5,667.0,581.0,786.0,733.5,NaN,998.0,805.0,730.0,934.5,691.5,717.0,759.5,731.0,610.5,531.5,340.0,1035.5,328.5,799.5,1308.5,718.5,468.5,440.5,892.5,431.0,1007.5,819.5,463.5,1099.0,768.0,412.5,577.5,507.0,139.5,1451.0,59.5,860.5,715.5,911.0,778.0,47.5,715.5,415.0,717.5,306.5,1150.5,689.5,334.5,457.0,235.5,697.5,432.5,253.0,780.5,345.5,NaN,441.5,176.5,1077.0,266.0,149.5,724.0,716.5,790.5,1407.0,328.5,1315.0,718.5,672.5,727.0,NaN,NaN,NaN,704.5,287.0,1373.0,827.0,736.5,524.0
1459,1460.0,268.5,667.0,760.0,827.5,733.5,NaN,998.0,805.0,730.0,934.5,691.5,372.5,759.5,731.0,610.5,531.5,340.0,1035.5,578.5,340.0,584.0,718.5,246.5,220.0,892.5,431.0,310.5,819.5,463.5,1099.0,768.0,946.0,294.5,1189.0,89.5,1365.5,245.0,1060.5,715.5,911.0,778.0,792.5,962.0,415.0,717.5,505.0,1150.5,689.5,334.5,1181.0,816.5,697.5,1093.0,591.5,780.5,345.5,NaN,441.5,413.0,176.5,266.0,225.5,724.0,716.5,790.5,1459.0,1094.5,626.5,718.5,672.5,727.0,NaN,NaN,NaN,704.5,688.0,795.5,827.0,736.5,591.0

In [187]:
data['Rank of MSSubClass'] = data.MSSubClass.rank(ascending = False)

In [188]:
data.head(2)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Rank of MSSubClass
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,546.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,1192.5

In [190]:
data.sort_values('MSSubClass') # see here the rank values of MSSubClass ---- use ascending as False in Rank function

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Rank of MSSubClass
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,None,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500,1192.5
888,889,20,RL,95.0,15865,Pave,NaN,IR1,Lvl,AllPub,Inside,Mod,NAmes,Norm,Norm,1Fam,1Story,8,6,1970,1970,Flat,Tar&Grv,Wd Sdng,Wd Sdng,None,0.0,Gd,Gd,PConc,TA,Gd,Gd,ALQ,351,Rec,823,1043,2217,GasA,Ex,Y,SBrkr,2217,0,0,2217,1,0,2,0,4,1,Gd,8,Typ,1,TA,Attchd,1970.0,Unf,2,621,TA,TA,Y,81,207,0,0,224,0,NaN,NaN,NaN,0,10,2007,WD,Normal,268000,1192.5
889,890,20,RL,128.0,12160,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Feedr,Norm,1Fam,1Story,6,4,1953,1953,Hip,CompShg,Wd Sdng,Wd Sdng,BrkFace,90.0,TA,TA,CBlock,TA,TA,No,BLQ,1024,Unf,0,481,1505,GasA,Ex,Y,SBrkr,1505,0,0,1505,1,0,1,0,2,1,TA,6,Typ,1,TA,Attchd,1953.0,RFn,2,505,TA,TA,Y,0,0,0,162,0,0,NaN,NaN,NaN,0,2,2009,WD,Normal,149500,1192.5
892,893,20,RL,70.0,8414,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,1Fam,1Story,6,8,1963,2003,Hip,CompShg,HdBoard,HdBoard,None,0.0,TA,TA,CBlock,TA,TA,No,GLQ,663,Unf,0,396,1059,GasA,TA,Y,SBrkr,1068,0,0,1068,0,1,1,0,3,1,TA,6,Typ,0,NaN,Attchd,1963.0,RFn,1,264,TA,TA,Y,192,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2006,WD,Normal,154500,1192.5
893,894,20,RL,NaN,13284,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,PosN,Norm,1Fam,1Story,5,5,1954,1954,Gable,CompShg,Wd Sdng,Plywood,None,0.0,TA,TA,PConc,Gd,TA,Mn,BLQ,1064,Unf,0,319,1383,GasA,TA,Y,SBrkr,1383,0,0,1383,1,0,1,0,3,1,TA,6,Typ,1,Gd,Attchd,1954.0,Unf,1,354,TA,TA,Y,511,116,0,0,0,0,NaN,GdPrv,NaN,0,6,2008,WD,Normal,165000,1192.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520,521,190,RL,60.0,10800,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,2fmCon,2Story,4,7,1900,2000,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,BrkTil,NaN,NaN,NaN,NaN,0,NaN,0,0,0,GasA,TA,N,FuseA,694,600,0,1294,0,0,2,0,3,2,TA,7,Typ,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,220,114,210,0,0,0,NaN,NaN,NaN,0,8,2008,WD,Normal,106250,15.5
1266,1267,190,RM,60.0,10120,Pave,NaN,IR1,Bnk,AllPub,Inside,Gtl,OldTown,Feedr,Norm,2fmCon,2.5Unf,7,4,1910,1950,Hip,CompShg,Wd Sdng,Wd Sdng,None,0.0,Fa,TA,CBlock,TA,TA,No,Unf,0,Unf,0,925,925,GasA,TA,N,FuseF,964,925,0,1889,0,0,1,1,4,2,TA,9,Typ,1,Gd,Detchd,1960.0,Unf,1,308,TA,TA,N,0,0,264,0,0,0,NaN,MnPrv,NaN,0,1,2007,WD,Normal,122000,15.5
48,49,190,RM,33.0,4456,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,2fmCon,2Story,4,5,1920,2008,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0,Unf,0,736,736,GasA,Gd,Y,SBrkr,736,716,0,1452,0,0,2,0,2,3,TA,8,Typ,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,N,0,0,102,0,0,0,NaN,NaN,NaN,0,6,2009,New,Partial,113000,15.5
1062,1063,190,RM,85.0,13600,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,2fmCon,2Story,5,5,1900,1950,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0,Unf,0,662,662,GasA,TA,N,SBrkr,1422,915,0,2337,0,0,2,0,5,2,TA,10,Min2,0,NaN,Detchd,1945.0,Unf,2,560,TA,TA,Y,0,57,0,0,0,0,NaN,NaN,NaN,0,9,2007,WD,Normal,90000,15.5
861,862,190,RL,75.0,11625,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,2fmCon,1Story,5,4,1965,1965,Hip,CompShg,Plywood,HdBoard,None,0.0,TA,TA,PConc,TA,TA,Mn,BLQ,841,Unf,0,198,1039,GasA,Ex,Y,SBrkr,1039,0,0,1039,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Unf,2,504,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal,131500,15.5

In [ ]:
# groupby

In [191]:
g = data.groupby('Street')

In [192]:
g

In [197]:
for i,j in g:
    print(i)
    print(j)
    
# This gives grouped datas for the unique values of Street feature

Grvl
        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
52      53          90       RM        110.0     8472   Grvl   NaN      IR2
335    336         190       RL          NaN   164660   Grvl   NaN      IR1
582    583          90       RL         81.0    11841   Grvl   NaN      Reg
812    813          20  C (all)         66.0     8712   Grvl   NaN      Reg
1061  1062          30  C (all)        120.0    18000   Grvl   NaN      Reg
1184  1185          20       RL         50.0    35133   Grvl   NaN      Reg

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
52           Bnk    AllPub    Corner       Mod       IDOTRR       RRNn
335          HLS    AllPub    Corner       Sev       Timber       Norm
582          Lvl    AllPub    Inside       Gtl      Edwards       Norm
812          Bnk    AllPub    Inside       Mod       IDOTRR       Norm
1061         Low    AllPub    Inside       Gtl       IDOTRR       Norm
1184         Lvl    AllPub    Inside       Mod       Timber       Norm

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
52         Norm   Duplex     1Story            5            5       1963
335        Norm   2fmCon     1.5Fin            5            6       1965
582        Norm   Duplex     SFoyer            6            5       1990
812        Norm     1Fam     1Story            5            5       1952
1061       Norm     1Fam     1Story            3            4       1935
1184       Norm     1Fam     1Story            5            4       1963

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
52            1963     Gable  CompShg     Wd Sdng     Wd Sdng       None
335           1965     Gable  CompShg     Plywood     Plywood       None
582           1990     Gable  CompShg     HdBoard     HdBoard    BrkFace
812           1952       Hip  CompShg     Wd Sdng     Wd Sdng       None
1061          1950     Gable  CompShg     MetalSd     MetalSd       None
1184          1963       Hip  CompShg     MetalSd     MetalSd    BrkFace

      MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond  \
52           0.0        Fa        TA     CBlock       Gd       TA
335          0.0        TA        TA     CBlock       TA       TA
582        104.0        TA        Gd     CBlock       Gd       TA
812          0.0        Fa        TA     CBlock       TA       TA
1061         0.0        Fa        TA     CBlock       TA       TA
1184       226.0        TA        TA     CBlock       TA       TA

     BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  \
52             Gd          LwQ         104          GLQ         712
335            Gd          ALQ        1249          BLQ         147
582            Av          GLQ         816          Unf           0
812            Av          Unf           0          Unf           0
1061           No          Unf           0          Unf           0
1184           Gd          Rec        1159          Unf           0

      BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  \
52            0          816    GasA        TA          N      SBrkr
335         103         1499    GasA        Ex          Y      SBrkr
582           0          816    GasA        TA          Y      SBrkr
812         540          540    GasA        TA          N      FuseA
1061        894          894    GasA        TA          Y      SBrkr
1184        413         1572    GasA        Gd          Y      SBrkr

      1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  \
52         816         0             0        816             1             0
335       1619       167             0       1786             2             0
582        816         0             0        816             1             0
812       1044         0             0       1044             0             0
1061       894         0             0        894             0             0
1184      1572         0             0       1572             1             0

      FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  \
52           1         0             2             1          TA
335          2         0             3             1          TA
582          1         0             3             1          TA
812          1         0             2             1          Fa
1061         1         0             2             1          TA
1184         1         1             3             1          TA

      TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt  \
52               5        Typ           0         NaN    CarPort       1963.0
335              7        Typ           2          Gd     Attchd       1965.0
582              5        Typ           0         NaN        NaN          NaN
812              4        Typ           0         NaN    Basment       1952.0
1061             6        Typ           0         NaN     Detchd       1994.0
1184             5        Typ           2          TA     2Types       1963.0

     GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  \
52            Unf           2         516         TA         TA          Y
335           Fin           2         529         TA         TA          Y
582           NaN           0           0        NaN        NaN          Y
812           Unf           2         504         TA         TA          N
1061          RFn           3        1248         TA         TA          Y
1184          RFn           3         995         TA         TA          Y

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
52           106            0              0          0            0
335          670            0              0          0            0
582            0           32              0          0            0
812            0            0              0          0            0
1061           0           20              0          0            0
1184           0          263              0          0          263

      PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold SaleType  \
52           0    NaN   NaN         NaN        0       5    2010       WD
335          0    NaN   NaN        Shed      700       8    2008       WD
582          0    NaN   NaN         NaN        0       5    2007       WD
812          0    NaN   NaN        Shed       54       6    2010       WD
1061         0    NaN   NaN        Shed      560       8    2008    ConLD
1184         0    NaN   NaN         NaN        0       5    2007       WD

     SaleCondition  SalePrice  Rank of MSSubClass
52          Normal     110000               216.5
335         Normal     228950                15.5
582         Normal     118500               216.5
812         Alloca      55993              1192.5
1061        Normal      81000               890.0
1184        Normal     186700              1192.5
Pave
        Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg
1        2          20       RL         80.0     9600   Pave   NaN      Reg
2        3          60       RL         68.0    11250   Pave   NaN      IR1
3        4          70       RL         60.0     9550   Pave   NaN      IR1
4        5          60       RL         84.0    14260   Pave   NaN      IR1
...    ...         ...      ...          ...      ...    ...   ...      ...
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg

     LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0            Lvl    AllPub    Inside       Gtl      CollgCr       Norm
1            Lvl    AllPub       FR2       Gtl      Veenker      Feedr
2            Lvl    AllPub    Inside       Gtl      CollgCr       Norm
3            Lvl    AllPub    Corner       Gtl      Crawfor       Norm
4            Lvl    AllPub       FR2       Gtl      NoRidge       Norm
...          ...       ...       ...       ...          ...        ...
1455         Lvl    AllPub    Inside       Gtl      Gilbert       Norm
1456         Lvl    AllPub    Inside       Gtl       NWAmes       Norm
1457         Lvl    AllPub    Inside       Gtl      Crawfor       Norm
1458         Lvl    AllPub    Inside       Gtl        NAmes       Norm
1459         Lvl    AllPub    Inside       Gtl      Edwards       Norm

     Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0          Norm     1Fam     2Story            7            5       2003
1          Norm     1Fam     1Story            6            8       1976
2          Norm     1Fam     2Story            7            5       2001
3          Norm     1Fam     2Story            7            5       1915
4          Norm     1Fam     2Story            8            5       2000
...         ...      ...        ...          ...          ...        ...
1455       Norm     1Fam     2Story            6            5       1999
1456       Norm     1Fam     1Story            6            6       1978
1457       Norm     1Fam     2Story            7            9       1941
1458       Norm     1Fam     1Story            5            6       1950
1459       Norm     1Fam     1Story            5            6       1965

      YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0             2003     Gable  CompShg     VinylSd     VinylSd    BrkFace
1             1976     Gable  CompShg     MetalSd     MetalSd       None
2             2002     Gable  CompShg     VinylSd     VinylSd    BrkFace
3             1970     Gable  CompShg     Wd Sdng     Wd Shng       None
4             2000     Gable  CompShg     VinylSd     VinylSd    BrkFace
...            ...       ...      ...         ...         ...        ...
1455          2000     Gable  CompShg     VinylSd     VinylSd       None
1456          1988     Gable  CompShg     Plywood     Plywood      Stone
1457          2006     Gable  CompShg     CemntBd     CmentBd       None
1458          1996       Hip  CompShg     MetalSd     MetalSd       None
1459          1965     Gable  CompShg     HdBoard     HdBoard       None

      MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond  \
0          196.0        Gd        TA      PConc       Gd       TA
1            0.0        TA        TA     CBlock       Gd       TA
2          162.0        Gd        TA      PConc       Gd       TA
3            0.0        TA        TA     BrkTil       TA       Gd
4          350.0        Gd        TA      PConc       Gd       TA
...          ...       ...       ...        ...      ...      ...
1455         0.0        TA        TA      PConc       Gd       TA
1456       119.0        TA        TA     CBlock       Gd       TA
1457         0.0        Ex        Gd      Stone       TA       Gd
1458         0.0        TA        TA     CBlock       TA       TA
1459         0.0        Gd        TA     CBlock       TA       TA

     BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  \
0              No          GLQ         706          Unf           0
1              Gd          ALQ         978          Unf           0
2              Mn          GLQ         486          Unf           0
3              No          ALQ         216          Unf           0
4              Av          GLQ         655          Unf           0
...           ...          ...         ...          ...         ...
1455           No          Unf           0          Unf           0
1456           No          ALQ         790          Rec         163
1457           No          GLQ         275          Unf           0
1458           Mn          GLQ          49          Rec        1029
1459           No          BLQ         830          LwQ         290

      BsmtUnfSF  TotalBsmtSF Heating HeatingQC CentralAir Electrical  \
0           150          856    GasA        Ex          Y      SBrkr
1           284         1262    GasA        Ex          Y      SBrkr
2           434          920    GasA        Ex          Y      SBrkr
3           540          756    GasA        Gd          Y      SBrkr
4           490         1145    GasA        Ex          Y      SBrkr
...         ...          ...     ...       ...        ...        ...
1455        953          953    GasA        Ex          Y      SBrkr
1456        589         1542    GasA        TA          Y      SBrkr
1457        877         1152    GasA        Ex          Y      SBrkr
1458          0         1078    GasA        Gd          Y      FuseA
1459        136         1256    GasA        Gd          Y      SBrkr

      1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  BsmtHalfBath  \
0          856       854             0       1710             1             0
1         1262         0             0       1262             0             1
2          920       866             0       1786             1             0
3          961       756             0       1717             1             0
4         1145      1053             0       2198             1             0
...        ...       ...           ...        ...           ...           ...
1455       953       694             0       1647             0             0
1456      2073         0             0       2073             1             0
1457      1188      1152             0       2340             0             0
1458      1078         0             0       1078             1             0
1459      1256         0             0       1256             1             0

      FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr KitchenQual  \
0            2         1             3             1          Gd
1            2         0             3             1          TA
2            2         1             3             1          Gd
3            1         0             3             1          Gd
4            2         1             4             1          Gd
...        ...       ...           ...           ...         ...
1455         2         1             3             1          TA
1456         2         0             3             1          TA
1457         2         0             4             1          Gd
1458         1         0             2             1          Gd
1459         1         1             3             1          TA

      TotRmsAbvGrd Functional  Fireplaces FireplaceQu GarageType  GarageYrBlt  \
0                8        Typ           0         NaN     Attchd       2003.0
1                6        Typ           1          TA     Attchd       1976.0
2                6        Typ           1          TA     Attchd       2001.0
3                7        Typ           1          Gd     Detchd       1998.0
4                9        Typ           1          TA     Attchd       2000.0
...            ...        ...         ...         ...        ...          ...
1455             7        Typ           1          TA     Attchd       1999.0
1456             7       Min1           2          TA     Attchd       1978.0
1457             9        Typ           2          Gd     Attchd       1941.0
1458             5        Typ           0         NaN     Attchd       1950.0
1459             6        Typ           0         NaN     Attchd       1965.0

     GarageFinish  GarageCars  GarageArea GarageQual GarageCond PavedDrive  \
0             RFn           2         548         TA         TA          Y
1             RFn           2         460         TA         TA          Y
2             RFn           2         608         TA         TA          Y
3             Unf           3         642         TA         TA          Y
4             RFn           3         836         TA         TA          Y
...           ...         ...         ...        ...        ...        ...
1455          RFn           2         460         TA         TA          Y
1456          Unf           2         500         TA         TA          Y
1457          RFn           1         252         TA         TA          Y
1458          Unf           1         240         TA         TA          Y
1459          Fin           1         276         TA         TA          Y

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0              0           61              0          0            0
1            298            0              0          0            0
2              0           42              0          0            0
3              0           35            272          0            0
4            192           84              0          0            0
...          ...          ...            ...        ...          ...
1455           0           40              0          0            0
1456         349            0              0          0            0
1457           0           60              0          0            0
1458         366            0            112          0            0
1459         736           68              0          0            0

      PoolArea PoolQC  Fence MiscFeature  MiscVal  MoSold  YrSold SaleType  \
0            0    NaN    NaN         NaN        0       2    2008       WD
1            0    NaN    NaN         NaN        0       5    2007       WD
2            0    NaN    NaN         NaN        0       9    2008       WD
3            0    NaN    NaN         NaN        0       2    2006       WD
4            0    NaN    NaN         NaN        0      12    2008       WD
...        ...    ...    ...         ...      ...     ...     ...      ...
1455         0    NaN    NaN         NaN        0       8    2007       WD
1456         0    NaN  MnPrv         NaN        0       2    2010       WD
1457         0    NaN  GdPrv        Shed     2500       5    2010       WD
1458         0    NaN    NaN         NaN        0       4    2010       WD
1459         0    NaN    NaN         NaN        0       6    2008       WD

     SaleCondition  SalePrice  Rank of MSSubClass
0           Normal     208500               546.0
1           Normal     181500              1192.5
2           Normal     223500               546.0
3          Abnorml     140000               366.5
4           Normal     250000               546.0
...            ...        ...                 ...
1455        Normal     175000               546.0
1456        Normal     210000              1192.5
1457        Normal     266500               366.5
1458        Normal     142125              1192.5
1459        Normal     147500              1192.5

[1454 rows x 82 columns]

In [198]:
g.get_group('Grvl')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Rank of MSSubClass
52,53,90,RM,110.0,8472,Grvl,NaN,IR2,Bnk,AllPub,Corner,Mod,IDOTRR,RRNn,Norm,Duplex,1Story,5,5,1963,1963,Gable,CompShg,Wd Sdng,Wd Sdng,None,0.0,Fa,TA,CBlock,Gd,TA,Gd,LwQ,104,GLQ,712,0,816,GasA,TA,N,SBrkr,816,0,0,816,1,0,1,0,2,1,TA,5,Typ,0,NaN,CarPort,1963.0,Unf,2,516,TA,TA,Y,106,0,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,110000,216.5
335,336,190,RL,NaN,164660,Grvl,NaN,IR1,HLS,AllPub,Corner,Sev,Timber,Norm,Norm,2fmCon,1.5Fin,5,6,1965,1965,Gable,CompShg,Plywood,Plywood,None,0.0,TA,TA,CBlock,TA,TA,Gd,ALQ,1249,BLQ,147,103,1499,GasA,Ex,Y,SBrkr,1619,167,0,1786,2,0,2,0,3,1,TA,7,Typ,2,Gd,Attchd,1965.0,Fin,2,529,TA,TA,Y,670,0,0,0,0,0,NaN,NaN,Shed,700,8,2008,WD,Normal,228950,15.5
582,583,90,RL,81.0,11841,Grvl,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,Duplex,SFoyer,6,5,1990,1990,Gable,CompShg,HdBoard,HdBoard,BrkFace,104.0,TA,Gd,CBlock,Gd,TA,Av,GLQ,816,Unf,0,0,816,GasA,TA,Y,SBrkr,816,0,0,816,1,0,1,0,3,1,TA,5,Typ,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,Y,0,32,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,118500,216.5
812,813,20,C (all),66.0,8712,Grvl,NaN,Reg,Bnk,AllPub,Inside,Mod,IDOTRR,Norm,Norm,1Fam,1Story,5,5,1952,1952,Hip,CompShg,Wd Sdng,Wd Sdng,None,0.0,Fa,TA,CBlock,TA,TA,Av,Unf,0,Unf,0,540,540,GasA,TA,N,FuseA,1044,0,0,1044,0,0,1,0,2,1,Fa,4,Typ,0,NaN,Basment,1952.0,Unf,2,504,TA,TA,N,0,0,0,0,0,0,NaN,NaN,Shed,54,6,2010,WD,Alloca,55993,1192.5
1061,1062,30,C (all),120.0,18000,Grvl,NaN,Reg,Low,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,3,4,1935,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,Fa,TA,CBlock,TA,TA,No,Unf,0,Unf,0,894,894,GasA,TA,Y,SBrkr,894,0,0,894,0,0,1,0,2,1,TA,6,Typ,0,NaN,Detchd,1994.0,RFn,3,1248,TA,TA,Y,0,20,0,0,0,0,NaN,NaN,Shed,560,8,2008,ConLD,Normal,81000,890.0
1184,1185,20,RL,50.0,35133,Grvl,NaN,Reg,Lvl,AllPub,Inside,Mod,Timber,Norm,Norm,1Fam,1Story,5,4,1963,1963,Hip,CompShg,MetalSd,MetalSd,BrkFace,226.0,TA,TA,CBlock,TA,TA,Gd,Rec,1159,Unf,0,413,1572,GasA,Gd,Y,SBrkr,1572,0,0,1572,1,0,1,1,3,1,TA,5,Typ,2,TA,2Types,1963.0,RFn,3,995,TA,TA,Y,0,263,0,0,263,0,NaN,NaN,NaN,0,5,2007,WD,Normal,186700,1192.5

In [200]:
g.max() # this shows max values in the groups. also use min, mean,median

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageYrBlt,GarageCars,GarageArea,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Rank of MSSubClass
Street,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Grvl,1185,190,RM,120.0,164660,Reg,Lvl,AllPub,Inside,Sev,Timber,RRNn,Norm,Duplex,SFoyer,6,6,1990,1990,Hip,CompShg,Wd Sdng,Wd Sdng,226.0,TA,TA,CBlock,1249,712,894,1572,GasA,TA,Y,1619,167,0,1786,2,0,2,1,3,1,TA,7,Typ,2,1994.0,3,1248,Y,670,263,0,0,263,0,700,8,2010,WD,Normal,228950,1192.5
Pave,1460,190,RM,313.0,215245,Reg,Lvl,NoSeWa,Inside,Sev,Veenker,RRNn,RRNn,TwnhsE,SLvl,10,9,2010,2010,Shed,WdShngl,WdShing,Wd Shng,1600.0,TA,TA,Wood,5644,1474,2336,6110,Wall,TA,Y,4692,2065,572,5642,3,2,3,2,8,3,TA,14,Typ,3,2010.0,4,1418,Y,857,547,552,508,480,738,15500,12,2010,WD,Partial,755000,1192.5

In [201]:
g.count()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Rank of MSSubClass
Street,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Grvl,6,6,6,5,6,0,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6,2,5,5,5,6,6,5,5,6,6,6,6,6,6,6,0,0,3,6,6,6,6,6,6,6
Pave,1454,1454,1454,1196,1454,91,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1446,1446,1454,1454,1454,1417,1417,1416,1417,1454,1416,1454,1454,1454,1454,1454,1454,1453,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,1454,768,1374,1374,1374,1454,1454,1374,1374,1454,1454,1454,1454,1454,1454,1454,7,281,51,1454,1454,1454,1454,1454,1454,1454

In [202]:
g.describe()

            Id                                                                \
         count        mean         std   min     25%    50%      75%     max
Street
Grvl       6.0  672.000000  433.388509  53.0  397.75  698.0   999.75  1185.0
Pave    1454.0  730.741403  421.697157   1.0  366.25  730.5  1095.75  1460.0

       MSSubClass                                                       \
            count       mean        std   min   25%   50%   75%    max
Street
Grvl          6.0  73.333333  65.929255  20.0  22.5  60.0  90.0  190.0
Pave       1454.0  56.829436  42.197743  20.0  20.0  50.0  70.0  190.0

       LotFrontage                                                        \
             count       mean        std   min   25%   50%    75%    max
Street
Grvl           5.0  85.400000  29.373457  50.0  66.0  81.0  110.0  120.0
Pave        1196.0  69.985786  24.255694  21.0  59.0  69.0   80.0  313.0

       LotArea                                                        \
         count          mean           std     min      25%      50%
Street
Grvl       6.0  41136.333333  61328.523180  8472.0  9494.25  14920.5
Pave    1454.0  10390.475241   9121.771083  1300.0  7536.25   9475.0

                           OverallQual                                     \
             75%       max       count      mean       std  min  25%  50%
Street
Grvl    30849.75  164660.0         6.0  4.833333  0.983192  3.0  5.0  5.0
Pave    11596.00  215245.0      1454.0  6.104539  1.382247  1.0  5.0  6.0

                  OverallCond                                                \
        75%   max       count      mean       std  min   25%  50%  75%  max
Street
Grvl    5.0   6.0         6.0  4.833333  0.752773  4.0  4.25  5.0  5.0  6.0
Pave    7.0  10.0      1454.0  5.578404  1.113195  1.0  5.00  5.0  6.0  9.0

       YearBuilt                                                            \
           count         mean        std     min      25%     50%      75%
Street
Grvl         6.0  1961.333333  18.007406  1935.0  1954.75  1963.0  1964.50
Pave      1454.0  1971.308803  30.239994  1872.0  1954.00  1973.0  2000.75

               YearRemodAdd                                                   \
           max        count         mean        std     min      25%     50%
Street
Grvl    1990.0          6.0  1963.833333  14.274686  1950.0  1954.75  1963.0
Pave    2010.0       1454.0  1984.952545  20.626621  1950.0  1967.00  1994.0

                       MasVnrArea                                         \
           75%     max      count        mean         std  min  25%  50%
Street
Grvl    1964.5  1990.0        6.0   55.000000   93.532882  0.0  0.0  0.0
Pave    2004.0  2010.0     1446.0  103.887275  181.331047  0.0  0.0  0.0

                      BsmtFinSF1                                            \
          75%     max      count        mean         std  min   25%    50%
Street
Grvl     78.0   226.0        6.0  554.666667  588.901237  0.0  26.0  460.0
Pave    166.0  1600.0     1454.0  443.181568  455.675284  0.0   0.0  383.5

                        BsmtFinSF2                                         \
            75%     max      count        mean         std  min  25%  50%
Street
Grvl    1073.25  1249.0        6.0  143.166667  284.806191  0.0  0.0  0.0
Pave     711.00  5644.0     1454.0   46.150619  160.665915  0.0  0.0  0.0

                       BsmtUnfSF                                              \
           75%     max     count        mean         std  min     25%    50%
Street
Grvl    110.25   712.0       6.0  325.000000  357.285320  0.0   25.75  258.0
Pave      0.00  1474.0    1454.0  568.240028  442.006863  0.0  224.00  479.5

                       TotalBsmtSF                                          \
           75%     max       count         mean         std    min     25%
Street
Grvl    508.25   894.0         6.0  1022.833333  415.597121  540.0  816.00
Pave    808.00  2336.0      1454.0  1057.572215  438.928002    0.0  795.25

                               1stFlrSF                                  \
          50%      75%     max    count         mean         std    min
Street
Grvl    855.0  1347.75  1572.0      6.0  1126.833333  372.748932  816.0
Pave    992.0  1297.75  6110.0   1454.0  1162.774415  386.760629  334.0

                                      2ndFlrSF                               \
          25%     50%     75%     max    count        mean         std  min
Street
Grvl    835.5   969.0  1440.0  1619.0      6.0   27.833333   68.177465  0.0
Pave    882.0  1088.0  1391.0  4692.0   1454.0  348.309491  436.927452  0.0

                                LowQualFinSF                                 \
        25%  50%    75%     max        count      mean        std  min  25%
Street
Grvl    0.0  0.0    0.0   167.0          6.0  0.000000   0.000000  0.0  0.0
Pave    0.0  0.0  728.0  2065.0       1454.0  5.868638  48.721916  0.0  0.0

                        GrLivArea                                           \
        50%  75%    max     count         mean         std    min      25%
Street
Grvl    0.0  0.0    0.0       6.0  1154.666667  420.079358  816.0   835.50
Pave    0.0  0.0  572.0    1454.0  1516.952545  525.473949  334.0  1131.25

                                BsmtFullBath                                 \
           50%      75%     max        count      mean       std  min   25%
Street
Grvl     969.0  1440.00  1786.0          6.0  0.833333  0.752773  0.0  0.25
Pave    1465.0  1778.25  5642.0       1454.0  0.423659  0.517436  0.0  0.00

                      BsmtHalfBath                                          \
        50%  75%  max        count      mean       std  min  25%  50%  75%
Street
Grvl    1.0  1.0  2.0          6.0  0.000000  0.000000  0.0  0.0  0.0  0.0
Pave    0.0  1.0  3.0       1454.0  0.057772  0.239216  0.0  0.0  0.0  0.0

            FullBath                                              HalfBath  \
        max    count      mean       std  min  25%  50%  75%  max    count
Street
Grvl    0.0      6.0  1.166667  0.408248  1.0  1.0  1.0  1.0  2.0      6.0
Pave    2.0   1454.0  1.566713  0.550935  0.0  1.0  2.0  2.0  3.0   1454.0

                                                    BedroomAbvGr           \
            mean       std  min  25%  50%  75%  max        count     mean
Street
Grvl    0.166667  0.408248  0.0  0.0  0.0  0.0  1.0          6.0  2.50000
Pave    0.383769  0.503161  0.0  0.0  0.0  1.0  2.0       1454.0  2.86795

                                          KitchenAbvGr                      \
             std  min  25%  50%  75%  max        count      mean       std
Street
Grvl    0.547723  2.0  2.0  2.5  3.0  3.0          6.0  1.000000  0.000000
Pave    0.816488  0.0  2.0  3.0  3.0  8.0       1454.0  1.046768  0.220772

                                TotRmsAbvGrd                                \
        min  25%  50%  75%  max        count      mean       std  min  25%
Street
Grvl    1.0  1.0  1.0  1.0  1.0          6.0  5.333333  1.032796  4.0  5.0
Pave    0.0  1.0  1.0  1.0  3.0       1454.0  6.522696  1.625831  2.0  5.0

                        Fireplaces                                          \
        50%   75%   max      count      mean       std  min  25%  50%  75%
Street
Grvl    5.0  5.75   7.0        6.0  0.666667  1.032796  0.0  0.0  0.0  1.5
Pave    6.0  7.00  14.0     1454.0  0.612792  0.643139  0.0  0.0  1.0  1.0

            GarageYrBlt                                                  \
        max       count         mean        std     min     25%     50%
Street
Grvl    2.0         5.0  1967.400000  15.725775  1952.0  1963.0  1963.0
Pave    3.0      1374.0  1978.546579  24.710951  1900.0  1961.0  1980.0

                       GarageCars                                           \
           75%     max      count      mean       std  min  25%  50%   75%
Street
Grvl    1965.0  1994.0        6.0  2.000000  1.095445  0.0  2.0  2.0  2.75
Pave    2002.0  2010.0     1454.0  1.766162  0.745943  0.0  1.0  2.0  2.00

            GarageArea                                                    \
        max      count        mean         std  min    25%    50%    75%
Street
Grvl    3.0        6.0  632.000000  436.141720  0.0  507.0  522.5  878.5
Pave    4.0     1454.0  472.323934  212.466109  0.0  331.5  478.5  576.0

               WoodDeckSF                                                      \
           max      count        mean        std  min  25%  50%    75%    max
Street
Grvl    1248.0        6.0  129.333333  268.24367  0.0  0.0  0.0   79.5  670.0
Pave    1418.0     1454.0   94.099725  124.58721  0.0  0.0  0.0  168.0  857.0

       OpenPorchSF                                                      \
             count       mean         std  min  25%   50%   75%    max
Street
Grvl           6.0  52.500000  103.976440  0.0  0.0  10.0  29.0  263.0
Pave        1454.0  46.636176   66.110851  0.0  0.0  25.0  68.0  547.0

       EnclosedPorch                                                   \
               count       mean        std  min  25%  50%  75%    max
Street
Grvl             6.0   0.000000   0.000000  0.0  0.0  0.0  0.0    0.0
Pave          1454.0  22.044704  61.228893  0.0  0.0  0.0  0.0  552.0

       3SsnPorch                                                 ScreenPorch  \
           count      mean        std  min  25%  50%  75%    max       count
Street
Grvl         6.0  0.000000   0.000000  0.0  0.0  0.0  0.0    0.0         6.0
Pave      1454.0  3.423659  29.376979  0.0  0.0  0.0  0.0  508.0      1454.0

                                                         PoolArea            \
             mean         std  min  25%  50%  75%    max    count      mean
Street
Grvl    43.833333  107.369300  0.0  0.0  0.0  0.0  263.0      6.0  0.000000
Pave    14.942228   55.485352  0.0  0.0  0.0  0.0  480.0   1454.0  2.770289

                                             MiscVal                          \
              std  min  25%  50%  75%    max   count        mean         std
Street
Grvl     0.000000  0.0  0.0  0.0  0.0    0.0     6.0  219.000000  322.102468
Pave    40.259783  0.0  0.0  0.0  0.0  738.0  1454.0   42.764787  496.658543

                                        MoSold                                \
        min  25%   50%    75%      max   count      mean       std  min  25%
Street
Grvl    0.0  0.0  27.0  433.5    700.0     6.0  6.166667  1.471960  5.0  5.0
Pave    0.0  0.0   0.0    0.0  15500.0  1454.0  6.322558  2.707808  1.0  5.0

                        YrSold                                          \
        50%  75%   max   count         mean       std     min      25%
Street
Grvl    5.5  7.5   8.0     6.0  2008.333333  1.366260  2007.0  2007.25
Pave    6.0  8.0  12.0  1454.0  2007.813618  1.328001  2006.0  2007.00

                               SalePrice                               \
           50%     75%     max     count           mean           std
Street
Grvl    2008.0  2009.5  2010.0       6.0  130190.500000  65446.253991
Pave    2008.0  2009.0  2010.0    1454.0  181130.538514  79446.597317

                                                        Rank of MSSubClass  \
            min       25%       50%       75%       max              count
Street
Grvl    55993.0   88250.0  114250.0  169650.0  228950.0                6.0
Pave    34900.0  130000.0  163000.0  214000.0  755000.0             1454.0


              mean         std   min    25%     50%       75%     max
Street
Grvl    620.583333  532.814266  15.5  216.5  553.25  1116.875  1192.5
Pave    730.953576  408.437259  15.5  366.5  767.50  1192.500  1192.5

In [204]:
# g.plot()

In [205]:
data.groupby('Street').Utilities.count()

Street
Grvl       6
Pave    1454
Name: Utilities, dtype: int64

In [209]:
data.groupby('Street').LotArea.agg(['count','min','mean','max'])

        count   min          mean     max
Street
Grvl        6  8472  41136.333333  164660
Pave     1454  1300  10390.475241  215245

In [210]:
data.groupby('Street').LotArea.agg(['count','min','mean','max']).reset_index()

  Street  count   min          mean     max
0   Grvl      6  8472  41136.333333  164660
1   Pave   1454  1300  10390.475241  215245

In [212]:
data.groupby(['Street','Utilities']).LotArea.agg(['count','min','mean','max']).reset_index()

  Street Utilities  count    min          mean     max
0   Grvl    AllPub      6   8472  41136.333333  164660
1   Pave    AllPub   1453   1300  10387.732966  215245
2   Pave    NoSeWa      1  14375  14375.000000   14375

In [213]:
data.groupby(['Street','Utilities']).LotArea.agg(['count','min','mean','max'])

                  count    min          mean     max
Street Utilities
Grvl   AllPub         6   8472  41136.333333  164660
Pave   AllPub      1453   1300  10387.732966  215245
       NoSeWa         1  14375  14375.000000   14375

In [ ]:
# joins

In [214]:

# importing pandas
import pandas as pd
  
# Creating dataframe a
a = pd.DataFrame()
  
# Creating Dictionary
d = {'id': [1, 2, 10, 12],
     'val1': ['a', 'b', 'c', 'd']}
  
a = pd.DataFrame(d)
  
# Creating dataframe b
b = pd.DataFrame()
  
# Creating dictionary
d = {'id': [1, 2, 9, 8],
     'val1': ['p', 'q', 'r', 's']}
b = pd.DataFrame(d)
  
# inner join
df = pd.merge(a, b, on='id', how='inner')
df = pd.merge(a, b, on='id', how='left')
df = pd.merge(a, b, on='id', how='right')
df = pd.merge(a, b, on='id', how='outer')
df = pd.merge(a, b, left_index=True, right_index=True) # index join, it joins even the ids

  
# display dataframe
df

   id_x val1_x  id_y val1_y
0     1      a     1      p
1     2      b     2      q
2    10      c     9      r
3    12      d     8      s